In [2]:
import pickle
import networkx as nx
import numpy as np
import pandas as pd

In [3]:
file = open('NetSense_network.pkl', 'rb')
# dump information to that file
data = pickle.load(file)

# close the file
file.close()

print('Showing the pickled data:')

cnt = 0
for item in data:
    print('The data ', cnt, ' is : ', item)
    cnt += 1

Showing the pickled data:
The data  0  is :  1
The data  1  is :  2
The data  2  is :  3
The data  3  is :  4
The data  4  is :  5
The data  5  is :  6


In [4]:
#creating list of attributes
list_of_attributes = set([k for n in data[1].nodes for k in data[1].nodes[n].keys()])

#creating possible attribute values
attribute_values = dict((attribute, set() ) for attribute in list_of_attributes)

for sem in range(1,7):
    for node in data[sem].nodes():
        for attribute in list_of_attributes:
            attribute_values[attribute].add(data[sem].nodes[node][attribute])

attribute_values

#To apply PCA or other analysis on all attributes (i.e. including ethnicity) 
#one would have to create an attribute for each race, that is is_1, is_2 etc. 
#Because this attribute is not ordered. 

{'gaymarriage_': {1, 2, 3},
 'hometown_1': {1, 2, 3},
 'ethnicity_1': {1, 2, 3, 4},
 'marijuana_': {1, 2, 3},
 'deathpen_': {1, 2, 3},
 'premaritalsex_': {1, 2, 3},
 'abortion_': {1, 2, 3},
 'gender_1': {1, 2},
 'homosexual_': {1, 2, 3},
 'euthanasia_': {1, 2, 3},
 'political_': {1, 2, 3},
 'age_1': {1, 2}}

In [5]:
#creating table of attribute values
attributes = dict((i, 0) for i in range(1,7))
for i in range(1,7):
    attributes[i] = np.zeros([len(data[i].nodes), len(list_of_attributes)])

for sem in range(1,7):
    for i, node in enumerate(data[sem].nodes()):
        for j, attribute in enumerate(list_of_attributes):
            attributes[sem][i,j] = data[sem].nodes[node][attribute]

In [6]:
attributes

{1: array([[3., 1., 2., ..., 3., 1., 1.],
        [1., 1., 2., ..., 2., 1., 1.],
        [3., 1., 2., ..., 3., 3., 1.],
        ...,
        [1., 1., 4., ..., 2., 2., 2.],
        [2., 3., 1., ..., 2., 1., 2.],
        [3., 1., 1., ..., 3., 2., 2.]]),
 2: array([[1., 3., 1., ..., 3., 1., 2.],
        [1., 1., 1., ..., 1., 1., 2.],
        [3., 1., 1., ..., 3., 1., 1.],
        ...,
        [3., 1., 1., ..., 1., 1., 1.],
        [3., 2., 1., ..., 3., 1., 1.],
        [3., 1., 3., ..., 2., 3., 1.]]),
 3: array([[3., 2., 1., 1., 1., 3., 3., 2., 3., 3., 2., 1.],
        [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.],
        [2., 2., 1., 3., 1., 1., 1., 2., 1., 1., 2., 2.],
        [3., 1., 3., 3., 3., 3., 1., 2., 3., 3., 3., 1.],
        [3., 1., 1., 2., 1., 3., 3., 1., 3., 3., 1., 2.],
        [3., 1., 2., 1., 1., 1., 3., 2., 1., 3., 2., 1.],
        [3., 2., 1., 2., 1., 3., 1., 1., 3., 2., 1., 1.],
        [3., 2., 1., 1., 1., 3., 3., 2., 3., 2., 3., 2.],
        [1., 1., 1., 1., 1., 

In [7]:

ord_list_of_attributes = list_of_attributes - {'ethnicity_1', 'gender_1', 'hometown_1', 'age_1'}
print(ord_list_of_attributes)

#creating table of attribute values
ord_attributes = dict((i, 0) for i in range(1,7))
for i in range(1,7):
    ord_attributes[i] = np.zeros([len(data[i].nodes), len(ord_list_of_attributes)])

for sem in range(1,7):
    for i, node in enumerate(data[sem].nodes()):
        for j, attribute in enumerate(ord_list_of_attributes):
            ord_attributes[sem][i,j] = data[sem].nodes[node][attribute]
print(ord_attributes)

{'gaymarriage_', 'marijuana_', 'deathpen_', 'premaritalsex_', 'abortion_', 'homosexual_', 'euthanasia_', 'political_'}
{1: array([[3., 2., 3., 3., 3., 3., 3., 1.],
       [1., 3., 2., 2., 2., 2., 2., 1.],
       [3., 3., 3., 3., 3., 1., 3., 3.],
       [3., 2., 1., 3., 3., 3., 1., 3.],
       [2., 1., 2., 3., 3., 3., 1., 2.],
       [1., 1., 1., 1., 1., 1., 3., 2.],
       [2., 1., 2., 1., 1., 2., 1., 1.],
       [2., 3., 2., 1., 2., 1., 2., 2.],
       [3., 2., 1., 3., 3., 3., 3., 2.],
       [3., 3., 1., 3., 1., 3., 1., 3.],
       [1., 2., 1., 1., 1., 1., 3., 2.],
       [2., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 1., 3., 1., 3., 2., 1.],
       [1., 3., 1., 1., 1., 2., 1., 1.],
       [3., 3., 3., 3., 1., 3., 3., 3.],
       [1., 2., 1., 2., 1., 2., 3., 1.],
       [1., 2., 2., 3., 1., 1., 2., 1.],
       [1., 3., 3., 1., 1., 1., 3., 1.],
       [3., 3., 2., 2., 3., 3., 3., 3.],
       [3., 3., 1., 3., 1., 1., 3., 1.],
       [3., 3., 3., 3., 3., 3., 3., 1.],
       [3., 3., 

# Calc link polarity

In [8]:
def calc_link_polarity(agent1, agent2, th, attr_dif):
    return np.sum(np.abs(agent1 - agent2) / attr_dif ) / len(agent1) <= th

def calc_link_polarities(agents, th, attr_dif):
    N, A = agents.shape
    
    polarities = np.zeros([N,N])
    
    for i in range(0,N):
        for j in range(i+1,N):
            if calc_link_polarity(agents[i,:], agents[j,:], th, attr_dif):
                polarities[i,j] = 1 
            else:
                polarities[i,j] = -1
            polarities[j,i] = polarities[i, j]
    return polarities

def balanced_triad_density(polarities):
    N = polarities.shape[0]
    return (np.sum(np.matmul(polarities,polarities) * polarities) / 6 / (N*(N-1)*(N-2)/6) + 1)/2

In [9]:
a1 = np.array([0,0,0])
a2 = np.array([1,1,1])

calc_link_polarity(a1, a2, 0.35, 2 ), calc_link_polarity(a1, a1, 0.5, 2)

(False, True)

In [10]:
a = np.zeros([3,3])
a[0,1] = 1
a[0,2] = 1
a[1,2] = -1
a[1,0] = 1
a[2,0] = 1
a[2,1] = -1

balanced_triad_density(a)

0.0

In [11]:
polarities = calc_link_polarities(ord_attributes[1], 0.5, 2)

In [12]:
polarities

array([[ 0.,  1.,  1., ..., -1., -1.,  1.],
       [ 1.,  0., -1., ...,  1.,  1.,  1.],
       [ 1., -1.,  0., ..., -1., -1.,  1.],
       ...,
       [-1.,  1., -1., ...,  0.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  0., -1.],
       [ 1.,  1.,  1., ..., -1., -1.,  0.]])

In [13]:
balanced_triad_density(polarities)

0.7293682937092363

# Calc balanced triads in network

In [14]:
data[1].nodes

NodeView((75178, 30952, 13116, 62555, 26999, 10841, 17353, 86352, 53275, 77291, 18394, 36006, 57637, 71627, 75261, 19844, 25323, 40997, 52635, 45945, 72746, 15071, 46771, 29914, 52067, 37617, 30076, 71700, 19066, 51675, 63188, 79877, 14106, 76313, 82282, 85596, 10060, 75468, 46021, 23642, 50869, 68633, 18420, 68494, 39783, 21350, 66404, 85970, 59367, 13799, 62560, 16495, 34853, 67947, 50709, 70889, 86727, 45539, 14188, 89827, 11692, 82060, 66754, 66245, 46654, 32174, 58909, 25947, 34250, 18344, 38823, 22745, 26127, 38893, 31372, 68533, 31583, 49597, 73303, 46160, 25544, 51597, 49294, 51722, 66052, 53884, 51552, 80058, 10281, 45292, 32899, 26425, 78911, 23144, 44520, 50181, 88175, 63063))

In [15]:
for i, node in enumerate(data[1].nodes):
    print(node)
    if i > 10:
        break

75178
30952
13116
62555
26999
10841
17353
86352
53275
77291
18394
36006


Above was a test of order of nodes in networkx. So I assume that the order of adjacency matrix and the attribute matrix are equal. 

In [16]:
def get_triads(net):
    A = nx.adjacency_matrix(net).todense() 

    N = A.shape[0]

    triads = []

    for i in range(0,N):
        for j in range(i+1,N):
            if A[i,j] > 0:
                for k in range(j+1,N):
                    if A[i,k] > 0 and A[j,k] > 0:
                        triads.append((i,j,k))
    
    return triads


In [17]:
A = nx.adjacency_matrix(data[1]).todense() 

N = A.shape[0]

triads = []

for i in range(0,N):
    for j in range(i+1,N):
        if A[i,j] > 0:
            for k in range(j+1,N):
                if A[i,k] > 0 and A[j,k] > 0:
                    triads.append((i,j,k))
len(triads)

45

In [18]:
np.trace(np.linalg.matrix_power((A>0)*1,3))/6

45.0

In [19]:
def balanced_triad_density_network(polarities, triads):
    T = len(triads)
    dens = 0.
    for triad in triads:
        i, j, k = triad
        if polarities[i,j]*polarities[i,k]*polarities[k,j] >= 0:
            dens = dens + 1
    dens = dens / T
    return dens

In [20]:
balanced_triad_density_network(polarities, triads), balanced_triad_density(polarities)

(0.7555555555555555, 0.7293682937092363)

In [21]:
T = len(triads)
dens = 0.
for triad in triads:
    i, j, k = triad
    print(polarities[i,j])
    if polarities[i,j]*polarities[i,k]*polarities[k,j] >= 0:
        dens = dens + 1
dens = dens / T
dens

1.0
1.0
-1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
-1.0
1.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
1.0
-1.0
-1.0
1.0
1.0
1.0
1.0
-1.0
1.0
1.0
1.0
1.0
-1.0
-1.0


0.7555555555555555

# Attribute randomization

Randomization of all attributes

In [22]:
import random
a = list(range(0,5))
random.shuffle(a)
a

[1, 3, 0, 4, 2]

In [23]:
x = np.zeros([3,3])
x[0,1] = 1
x[0,2] = 2
x[1, 0] = 10
x[1,1] = 11
x[1,2] = 12
x[2,0] = 20
x[2,2] = 22
np.random.shuffle(x)
x

array([[ 0.,  1.,  2.],
       [20.,  0., 22.],
       [10., 11., 12.]])

In [24]:
def randomize_all_attributes(attr):
    N, A = attr.shape
    
    attr_rand = np.copy(attr)
    np.random.shuffle(attr_rand)
    
    return attr_rand

def compare_bal_triads(triads, agents, th, attr_dif, M):
    """
    triads - list of sets of node ids forming a triad
    agents - array of vectors of agent attributes
    th - threshold used
    attr_dif - max difference between attributes
    M - number of times to repeat randomization
    """
    polarities = calc_link_polarities(agents, th, attr_dif)
    bal_dens = balanced_triad_density_network(polarities, triads)
    
    bal_dens_rands = np.zeros(M)
    
    for i in range(0,M):
        agents_rand = randomize_all_attributes(agents)
        polarities_rand = calc_link_polarities(agents_rand, th, attr_dif)
        bal_dens_rands[i] = balanced_triad_density_network(polarities_rand, triads)
        
    pval = np.sum(bal_dens_rands >= bal_dens)
    
    return bal_dens_rands, bal_dens, pval

def compare_networks(data, th, attr_dif, M):
    pvals = np.zeros(6)
    vals = np.zeros(6)
    stds = np.zeros(6)
    difs = np.zeros(6)
    
    for n in range(1,7):
#         print(n)
        net = data[n]
        triads = get_triads(net)
        agents = ord_attributes[n]
        
        bal_dens_rands, bal_dens, pval = compare_bal_triads(triads, agents, th, attr_dif, M)
        pvals[n-1] = pval
        vals[n - 1] = bal_dens
        difs[n-1] = np.mean(bal_dens - bal_dens_rands)
        stds[n-1] = np.std(difs)
    return pvals, vals, difs, stds

In [25]:
bal_dens_rands, bal_dens = compare_bal_triads(triads, agents, 0.3, 2, 100)

NameError: name 'agents' is not defined

In [26]:
np.sum(bal_dens_rands > bal_dens), np.mean(bal_dens_rands) - bal_dens

NameError: name 'bal_dens_rands' is not defined

In [29]:
compare_networks(data, 0.5, 2, 100)

(array([45., 39., 75., 82., 32., 39.]),
 array([0.75555556, 0.76923077, 0.66666667, 0.65384615, 0.8       ,
        0.83333333]),
 array([ 0.02933333,  0.05538462, -0.03888889, -0.06461538,  0.096     ,
         0.0875    ]),
 array([0.01093189, 0.02133741, 0.02912672, 0.03990942, 0.05452482,
        0.06050603]))

In [230]:
n = 2
net = data[n]
triads = get_triads(net)
agents = ord_attributes[n]

In [30]:
A

matrix([[ 0, 11,  0, ...,  0,  0,  0],
        [11,  0, 61, ...,  0,  0,  0],
        [ 0, 61,  0, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0]])